name = "SGtSNEpi"
uuid = "e6c19c8d-e382-4a50-b2c6-174ddd647730"
authors = ["Nikos Pitsianis <nikos@cs.duke.edu>", "Dimitris Floros <fcdimitr@ece.auth.gr>", "Alexandros-Stavros Iliopoulos <ailiop@mit.edu>", "Xiaobai Sun <xiaobai@cs.duke.edu>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
